import numpy as np

width = 10

def tendon_lengths_test(rx, ry):
    # rx, ry are in radians
    A = np.np.sqrt(1 + np.tan(rx)**2 + np.tan(ry)**2)
    B = np.np.sqrt(np.tan(rx)**2 + np.tan(ry)**2)

    # 1) np.sin(theta/2) * np.cos(phi)
    val1 = 2 * width * np.np.sqrt((A - 1) / (2 * A)) * (np.tan(ry) / B)

    # 2) np.sin(theta/2) * np.cos(phi - 2/3 * pi)
    val2 = 2 * width * np.np.sqrt((A - 1) / (2 * A)) * ((-np.tan(ry) + np.np.sqrt(3) * np.tan(rx)) / (2 * B))

    # 3) np.sin(theta/2) * np.cos(phi - 4/3 * pi)
    val3 = 2 * width * np.np.sqrt((A - 1) / (2 * A)) * ((-np.tan(ry) - np.np.sqrt(3) * np.tan(rx)) / (2 * B))

    return np.array([val1, val2, val3])

def tendons_jacobian(x, y):

    w = width

    # d/rx val1
    dx_1 = -(w * np.tan(y) * 1/np.cos(x)**2 * np.tan(x) * (np.tan(x)**2 * (2 * np.sqrt(np.tan(x)**2 + np.tan(y)**2 + 1) - 3) + np.tan(y)**2 * (2 * np.sqrt(np.tan(x)**2 + np.tan(y)**2 + 1) - 3) + 2 * np.sqrt(np.tan(x)**2 + np.tan(y)**2 + 1) - 2)) / (np.sqrt(2) * (np.tan(x)**2 + np.tan(y)**2)**(3 / 2) * (np.tan(x)**2 + np.tan(y)**2 + 1)**(5 / 4) * np.sqrt(np.sqrt(np.tan(x)**2 + np.tan(y)**2 + 1) - 1))
    # d/ry val1
    dy_1 = -(w * 1/np.cos(x)**2 * np.tan(x) * 1/np.cos(y)**2 * (8 * np.tan(y)**2 * (np.tan(y)**2 + np.tan(x)**2 + 1)**(5 / 2) - 4 * np.tan(x)**2 * (np.tan(y)**2 + np.tan(x)**2 + 1)**(5 / 2) - 2 * np.tan(y)**4 * (np.tan(y)**2 + np.tan(x)**2 + 1)**(3 / 2) - 2 * np.tan(x)**2 * np.tan(y)**2 * (np.tan(y)**2 + np.tan(x)**2 + 1)**(3 / 2) + 18 * np.tan(y)**6 * np.sqrt(np.tan(y)**2 + np.tan(x)**2 + 1) + 30 * np.tan(x)**2 * np.tan(y)**4 * np.sqrt(np.tan(y)**2 + np.tan(x)**2 + 1) + 20 * np.tan(y)**4 * np.sqrt(np.tan(y)**2 + np.tan(x)**2 + 1) + 6 * np.tan(x)**4 * np.tan(y)**2 * np.sqrt(np.tan(y)**2 + np.tan(x)**2 + 1) + 10 * np.tan(x)**2 * np.tan(y)**2 * np.sqrt(np.tan(y)**2 + np.tan(x)**2 + 1) + 8 * np.tan(y)**2 * np.sqrt(np.tan(y)**2 + np.tan(x)**2 + 1) - 6 * np.tan(x)**6 * np.sqrt(np.tan(y)**2 + np.tan(x)**2 + 1) - 10 * np.tan(x)**4 * np.sqrt(np.tan(y)**2 + np.tan(x)**2 + 1) - 4 * np.tan(x)**2 * np.sqrt(np.tan(y)**2 + np.tan(x)**2 + 1) - 8 * np.tan(y)**8 - 20 * np.tan(x)**2 * np.tan(y)**6 - 39 * np.tan(y)**6 - 12 * np.tan(x)**4 * np.tan(y)**4 - 60 * np.tan(x)**2 * np.tan(y)**4 - 42 * np.tan(y)**4 + 4 * np.tan(x)**6 * np.tan(y)**2 - 3 * np.tan(x)**4 * np.tan(y)**2 - 20 * np.tan(x)**2 * np.tan(y)**2 - 16 * np.tan(y)**2 + 2 * np.tan(x)**2 * (np.tan(x)**2 + 1) * (2 * np.tan(x)**4 + 7 * np.tan(x)**2 + 4))) / (2**(3 / 2) * (np.tan(y)**2 + np.tan(x)**2)**(5 / 2) * (np.tan(y)**2 + np.tan(x)**2 + 1)**(9 / 4) * (np.sqrt(np.tan(y)**2 + np.tan(x)**2 + 1) - 1)**(3 / 2))

    # d/rx val2
    dx_2 = (w * 1/np.cos(x)**2 * (np.tan(x) * (np.tan(y) * (2 * np.sqrt(np.tan(x)**2 + np.tan(y)**2 + 1) - 2) + np.tan(y)**3 * (2 * np.sqrt(np.tan(x)**2 + np.tan(y)**2 + 1) - 3)) + np.sqrt(3) * np.tan(y)**2 * np.tan(x)**2 * (2 * np.sqrt(np.tan(x)**2 + np.tan(y)**2 + 1) - 1) + np.sqrt(3) * np.tan(y)**4 * (2 * np.sqrt(np.tan(x)**2 + np.tan(y)**2 + 1) - 2) + np.sqrt(3) * np.tan(y)**2 * (2 * np.sqrt(np.tan(x)**2 + np.tan(y)**2 + 1) - 2) + np.tan(y) * np.tan(x)**3 * (2 * np.sqrt(np.tan(x)**2 + np.tan(y)**2 + 1) - 3) + np.sqrt(3) * np.tan(x)**4)) / (2**(3 / 2) * (np.tan(x)**2 + np.tan(y)**2)**(3 / 2) * (np.tan(x)**2 + np.tan(y)**2 + 1)**(5 / 4) * np.sqrt(np.sqrt(np.tan(x)**2 + np.tan(y)**2 + 1) - 1))
    # d/rx val2
    dy_2 = -(3 * w * 1/np.cos(x)**2 * 1/np.cos(y)**2 * np.tan(y) * (np.sqrt(np.tan(y)**2 + np.tan(x)**2 + 1) * (2 * np.sqrt(3) * np.tan(y)**4 + 2 * np.tan(x) * np.tan(y)**3 + (2 * np.sqrt(3) * np.tan(x)**2 + 2 * np.sqrt(3)) * np.tan(y)**2 + (2 * np.tan(x)**3 + 2 * np.tan(x)) * np.tan(y)) - 2 * np.sqrt(3) * np.tan(y)**4 - 3 * np.tan(x) * np.tan(y)**3 + (-np.sqrt(3) * np.tan(x)**2 - 2 * np.sqrt(3)) * np.tan(y)**2 + (-3 * np.tan(x)**3 - 2 * np.tan(x)) * np.tan(y) + np.sqrt(3) * np.tan(x)**4)) / (2**(3 / 2) * (np.tan(y)**2 + np.tan(x)**2)**(5 / 2) * (np.tan(y)**2 + np.tan(x)**2 + 1)**(5 / 4) * np.sqrt(np.sqrt(np.tan(y)**2 + np.tan(x)**2 + 1) - 1)) - (5 * w * 1/np.cos(x)**2 * 1/np.cos(y)**2 * np.tan(y) * (np.sqrt(np.tan(y)**2 + np.tan(x)**2 + 1) * (2 * np.sqrt(3) * np.tan(y)**4 + 2 * np.tan(x) * np.tan(y)**3 + (2 * np.sqrt(3) * np.tan(x)**2 + 2 * np.sqrt(3)) * np.tan(y)**2 + (2 * np.tan(x)**3 + 2 * np.tan(x)) * np.tan(y)) - 2 * np.sqrt(3) * np.tan(y)**4 - 3 * np.tan(x) * np.tan(y)**3 + (-np.sqrt(3) * np.tan(x)**2 - 2 * np.sqrt(3)) * np.tan(y)**2 + (-3 * np.tan(x)**3 - 2 * np.tan(x)) * np.tan(y) + np.sqrt(3) * np.tan(x)**4)) / (2**(5 / 2) * (np.tan(y)**2 + np.tan(x)**2)**(3 / 2) * (np.tan(y)**2 + np.tan(x)**2 + 1)**(9 / 4) * np.sqrt(np.sqrt(np.tan(y)**2 + np.tan(x)**2 + 1) - 1)) + (w * 1/np.cos(x)**2 * ((1/np.cos(y)**2 * np.tan(y) * (2 * np.sqrt(3) * np.tan(y)**4 + 2 * np.tan(x) * np.tan(y)**3 + (2 * np.sqrt(3) * np.tan(x)**2 + 2 * np.sqrt(3)) * np.tan(y)**2 + (2 * np.tan(x)**3 + 2 * np.tan(x)) * np.tan(y))) / np.sqrt(np.tan(y)**2 + np.tan(x)**2 + 1) + np.sqrt(np.tan(y)**2 + np.tan(x)**2 + 1) * (8 * np.sqrt(3) * 1/np.cos(y)**2 * np.tan(y)**3 + 6 * np.tan(x) * 1/np.cos(y)**2 * np.tan(y)**2 + 2 * (2 * np.sqrt(3) * np.tan(x)**2 + 2 * np.sqrt(3)) * 1/np.cos(y)**2 * np.tan(y) + (2 * np.tan(x)**3 + 2 * np.tan(x)) * 1/np.cos(y)**2) - 8 * np.sqrt(3) * 1/np.cos(y)**2 * np.tan(y)**3 - 9 * np.tan(x) * 1/np.cos(y)**2 * np.tan(y)**2 + 2 * (-np.sqrt(3) * np.tan(x)**2 - 2 * np.sqrt(3)) * 1/np.cos(y)**2 * np.tan(y) + (-3 * np.tan(x)**3 - 2 * np.tan(x)) * 1/np.cos(y)**2)) / (2**(3 / 2) * (np.tan(y)**2 + np.tan(x)**2)**(3 / 2) * (np.tan(y)**2 + np.tan(x)**2 + 1)**(5 / 4) * np.sqrt(np.sqrt(np.tan(y)**2 + np.tan(x)**2 + 1) - 1)) - (w * 1/np.cos(x)**2 * 1/np.cos(y)**2 * np.tan(y) * (np.sqrt(np.tan(y)**2 + np.tan(x)**2 + 1) * (2 * np.sqrt(3) * np.tan(y)**4 + 2 * np.tan(x) * np.tan(y)**3 + (2 * np.sqrt(3) * np.tan(x)**2 + 2 * np.sqrt(3)) * np.tan(y)**2 + (2 * np.tan(x)**3 + 2 * np.tan(x)) * np.tan(y)) - 2 * np.sqrt(3) * np.tan(y)**4 - 3 * np.tan(x) * np.tan(y)**3 + (-np.sqrt(3) * np.tan(x)**2 - 2 * np.sqrt(3)) * np.tan(y)**2 + (-3 * np.tan(x)**3 - 2 * np.tan(x)) * np.tan(y) + np.sqrt(3) * np.tan(x)**4)) / (2**(5 / 2) * (np.tan(y)**2 + np.tan(x)**2)**(3 / 2) * (np.tan(y)**2 + np.tan(x)**2 + 1)**(7 / 4) * (np.sqrt(np.tan(y)**2 + np.tan(x)**2 + 1) - 1)**(3 / 2))

    # d/rx val3
    dx_3 = (w * 1/np.cos(x)**2 * (-np.sqrt(3) * np.tan(x)**4 + np.sqrt(np.tan(x)**2 + np.tan(y)**2 + 1) * (2 * np.tan(y) * np.tan(x)**3 - 2 * np.sqrt(3) * np.tan(y)**2 * np.tan(x)**2 + (2 * np.tan(y)**3 + 2 * np.tan(y)) * np.tan(x) - 2 * np.sqrt(3) * np.tan(y)**4 - 2 * np.sqrt(3) * np.tan(y)**2) - 3 * np.tan(y) * np.tan(x)**3 + np.sqrt(3) * np.tan(y)**2 * np.tan(x)**2 + (-3 * np.tan(y)**3 - 2 * np.tan(y)) * np.tan(x) + 2 * np.sqrt(3) * np.tan(y)**4 + 2 * np.sqrt(3) * np.tan(y)**2)) / (2**(3 / 2) * (np.tan(x)**2 + np.tan(y)**2)**(3 / 2) * (np.tan(x)**2 + np.tan(y)**2 + 1)**(5 / 4) * np.sqrt(np.sqrt(np.tan(x)**2 + np.tan(y)**2 + 1) - 1))
    # d/rx val3
    dy_3 = (w * 1/np.cos(x)**2 * 1/np.cos(y)**2 * (np.sqrt(np.tan(y)**2 + np.tan(x)**2 + 1) * (2 * np.sqrt(3) * np.tan(y)**9 - 6 * np.tan(x) * np.tan(y)**8 + (14 * np.sqrt(3) - 2 * np.sqrt(3) * np.tan(x)**2) * np.tan(y)**7 + (-14 * np.tan(x)**3 - 35 * np.tan(x)) * np.tan(y)**6 + (-2 * 3**(5 / 2) * np.tan(x)**4 - 11 * np.sqrt(3) * np.tan(x)**2 + 20 * np.sqrt(3)) * np.tan(y)**5 + (-6 * np.tan(x)**5 - 52 * np.tan(x)**3 - 40 * np.tan(x)) * np.tan(y)**4 + (-22 * np.sqrt(3) * np.tan(x)**6 - 64 * np.sqrt(3) * np.tan(x)**4 - 22 * np.sqrt(3) * np.tan(x)**2 + 8 * np.sqrt(3)) * np.tan(y)**3 + (6 * np.tan(x)**7 + np.tan(x)**5 - 18 * np.tan(x)**3 - 16 * np.tan(x)) * np.tan(y)**2 + (-8 * np.sqrt(3) * np.tan(x)**8 - 13 * 3**(3 / 2) * np.tan(x)**6 - 14 * 3**(3 / 2) * np.tan(x)**4 - 16 * np.sqrt(3) * np.tan(x)**2) * np.tan(y) + 4 * np.tan(x)**9 + 18 * np.tan(x)**7 + 22 * np.tan(x)**5 + 8 * np.tan(x)**3) - 10 * np.sqrt(3) * np.tan(y)**9 + 24 * np.tan(x) * np.tan(y)**8 + (np.tan(y)**2 + np.tan(x)**2 + 1)**(3 / 2) * (2 * np.sqrt(3) * np.tan(y)**7 - 2 * np.tan(x) * np.tan(y)**6 + (4 * np.sqrt(3) * np.tan(x)**2 + 2 * np.sqrt(3)) * np.tan(y)**5 + (-4 * np.tan(x)**3 - 2 * np.tan(x)) * np.tan(y)**4 + (2 * np.sqrt(3) * np.tan(x)**4 + 2 * np.sqrt(3) * np.tan(x)**2) * np.tan(y)**3 + (-2 * np.tan(x)**5 - 2 * np.tan(x)**3) * np.tan(y)**2) + (-2 * 3**(3 / 2) * np.tan(x)**2 - 28 * np.sqrt(3)) * np.tan(y)**7 + (62 * np.tan(x)**3 + 58 * np.tan(x)) * np.tan(y)**6 + (14 * 3**(3 / 2) * np.tan(x)**4 + 2 * np.sqrt(3) * np.tan(x)**2 - 26 * np.sqrt(3)) * np.tan(y)**5 + (42 * np.tan(x)**5 + 88 * np.tan(x)**3 + 50 * np.tan(x)) * np.tan(y)**4 + (62 * np.sqrt(3) * np.tan(x)**6 + 88 * np.sqrt(3) * np.tan(x)**4 + 8 * 3**(3 / 2) * np.tan(x)**2 - 8 * np.sqrt(3)) * np.tan(y)**3 + (-6 * np.tan(x)**7 + 2 * np.tan(x)**5 + 24 * np.tan(x)**3 + 16 * np.tan(x)) * np.tan(y)**2 + (8 * 3**(3 / 2) * np.tan(x)**8 + 58 * np.sqrt(3) * np.tan(x)**6 + 50 * np.sqrt(3) * np.tan(x)**4 + 16 * np.sqrt(3) * np.tan(x)**2) * np.tan(y) - 10 * np.tan(x)**9 - 28 * np.tan(x)**7 - 26 * np.tan(x)**5 - 8 * np.tan(x)**3)) / (2**(5 / 2) * (np.tan(y)**2 + np.tan(x)**2)**(5 / 2) * (np.tan(y)**2 + np.tan(x)**2 + 1)**(11 / 4) * (np.sqrt(np.tan(y)**2 + np.tan(x)**2 + 1) - 1)**(3 / 2))

    return np.array([[dx_1, dy_1], [dx_2, dy_2], [dx_3, dy_3]])

print(tendons_jacobian(np.radians(10), np.radians(20)))